### ISSUE TITLE
enable make log group and log stream

### ISSUE THREAD

**Issue by mitchbregs** [betfund/betfund-logger#6]

**Comment by mitchbregs** [comment]
What are your thoughts around this @leonkozlowski? The question really is - do we want to control the log groups/streams on our own, or let things happen as the coder wants them to?  My thoughts are - if it's just us 2, I trust that we are going to create the proper log groups and streams (on top of being the only people with access to our AWS Console) implemented in the code, but can see it spiraling out if we extend our team in the future. Open to whatever approach you think is most appropriate.

**Comment by mitchbregs** [comment]
What would need to change is setting to True:

https://github.com/betfund/betfund-logger/blob/0ff89a7a6fa66c557a8de0301f51d9e4b31dd27e/betfund_logger/cloud.py#L63

https://github.com/betfund/betfund-logger/blob/0ff89a7a6fa66c557a8de0301f51d9e4b31dd27e/betfund_logger/cloud.py#L64

**Comment by leonkozlowski** [comment]
I think we can leave it as manual creating

This will keep everything under control as well as prevent magic logs from appearing

**Comment by mitchbregs** [comment]
Awesome, agree. Closing this issue.
